# Generated by Django 4.2.4 on 2023-08-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rname', models.CharField(max_length=100)),
                ('Rdes', models.TextField()),
                ('Rtype', models.CharField(max_length=10)),
                ('Rcreated', models.DateField(auto_now_add=True)),
                ('pimage', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
