# Generated by Django 4.2.4 on 2023-08-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='pimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
