# Generated by Django 4.2.4 on 2023-08-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_server_pimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='Rid',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='server',
            name='Rdes',
            field=models.TextField(max_length=100),
        ),
    ]
