# Generated by Django 4.2.4 on 2023-08-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_server_rid_alter_server_rdes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='Rname',
            field=models.CharField(max_length=300),
        ),
    ]
