# Generated by Django 4.2.4 on 2023-08-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_server_rdes_alter_server_rname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='pimage',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
