# Generated by Django 4.2.4 on 2023-08-30 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_remove_server_rcreated_remove_server_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='pimage',
            new_name='Rimage',
        ),
    ]
