# Generated by Django 4.2.4 on 2023-08-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_rename_pimage_server_rimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='Rcreated',
            field=models.DateField(auto_now_add=True, default=True),
            preserve_default=False,
        ),
    ]
