# Generated by Django 4.2.4 on 2023-08-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_server_rcreated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='Rid',
        ),
        migrations.AddField(
            model_name='server',
            name='id',
            field=models.BigAutoField(auto_created=True, default=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
