# Generated by Django 4.2.4 on 2023-08-31 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipeCreatedAt',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipeImageUrl',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipeType',
        ),
    ]
