# Generated by Django 4.2.4 on 2023-08-31 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_remove_recipe_recipecreatedat_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recipe',
            table='recipe',
        ),
    ]
